### ISSUE TITLE
2024.6 beta5 issue

### ISSUE THREAD

**Issue by Repsionu** [hristo-atanasov/Tasmota-IRHVAC#140]
`Platform error 'climate' from integration 'tasmota_irhvac' - cannot import name 'MqttAvailability' from 'homeassistant.components.mqtt.mixins' (/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py)`

Latest HAOS beta, lost all climate units with IRHVAC :-(
Best, JR

**Comment by fotis3d** [comment]
Having the same issue with the new version of HA.

![image](https://github.com/hristo-atanasov/Tasmota-IRHVAC/assets/42974039/2fd27ac4-a993-426b-855b-08e93d746ea0)

**Comment by fragolinux** [comment]
i've issues too, after update to 2024.6 this night, my card disappeared and in logs i've just found this:

```
Registratore: homeassistant.util.loop
Fonte: util/loop.py:56
Prima occorrenza: 5 giugno 2024 alle ore 22:11:07 (1 occorrenze)
Ultima registrazione: 5 giugno 2024 alle ore 22:11:07

Detected blocking call to import_module with args ('custom_components.tasmota_irhvac.climate',) in /usr/src/homeassistant/homeassistant/loader.py, line 1281: return importlib.import_module(f"{self.pkg_path}.{platform_name}") inside the event loop Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config.py", line 1440, in _async_load_and_validate_platform_integration platform = await p_integration.integration.async_get_platform(domain) File "/usr/src/homeassistant/homeassistant/loader.py", line 1085, in async_get_platform platforms = await self.async_get_platforms((platform_name,)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1150, in async_get_platforms platforms.update(self._load_platforms(platform_names)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _load_platforms platform_name: self._load_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1249, in _load_platform cache[full_name] = self._import_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1281, in _import_platform return importlib.import_module(f"{self.pkg_path}.{platform_name}")
```

**Comment by ahmaddxb** [comment]
Same here from that 2024.6 update

**Comment by fragolinux** [comment]
found this other error while pushing "check configuration" in HA developer tools

`Platform error 'climate' from integration 'tasmota_irhvac' - cannot import name 'MqttAvailability' from 'homeassistant.components.mqtt.mixins' (/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py)`

**Comment by SinanMQTT** [comment]
Same issue here can not control my climate devices :(

> Configuration warnings
Platform error 'climate' from integration 'tasmota_irhvac' - cannot import name 'MqttAvailability' from 'homeassistant.components.mqtt.mixins' (/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py)
Platform error 'climate' from integration 'tasmota_irhvac' - cannot import name 'MqttAvailability' from 'homeassistant.components.mqtt.mixins' (/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py)
Platform error 'climate' from integration 'tasmota_irhvac' - cannot import name 'MqttAvailability' from 'homeassistant.components.mqtt.mixins' (/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py)

**Comment by TELY01** [comment]
> integration

I got the the same error after update HA Core to 2024.6.0

**Comment by nao-pon** [comment]
Due to a problem with LWT message handling, we have temporarily stopped handling LWT messages until the next version.

I have released Version 2024.6.0 as an emergency update, but we will address the issue of LWT message handling in the next version, but it will take some time.

**Comment by Repsionu** [comment]
Thanks for a speedy fix, IRHVAC online again :-)

**Comment by fragolinux** [comment]
confirmed, it's back!
but waiting for the fix, i let chatgpt create one basic dashboard with the settings i use the most for my tasmota ir blaster :D 

```
type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - type: button
        icon: mdi:fire
        name: Heat On
        show_name: true
        show_icon: true
        tap_action:
          action: call-service
          service: mqtt.publish
          service_data:
            topic: cmnd/WemosIR/IRsend
            payload: >-
              {"Protocol":"COOLIX","Bits":24,"Data":"0xB23FBC","DataLSB":"0x4DFC3D","Repeat":0,"IRHVAC":{"Vendor":"COOLIX","Model":-1,"Command":"Control","Mode":"Heat","Power":"On","Celsius":"On","Temp":30,"FanSpeed":"Max","SwingV":"Off","SwingH":"Off","Quiet":"Off","Turbo":"Off","Econo":"Off","Light":"Off","Filter":"Off","Clean":"Off","Beep":"Off","Sleep":-1,"iFeel":"Off","SensorTemp":null}}
      - type: button
        icon: mdi:fan
        name: Heat Swing On
        show_name: true
        show_icon: true
        tap_action:
          action: call-service
          service: mqtt.publish
          service_data:
            topic: cmnd/WemosIR/IRsend
            payload: >-
              {"Protocol":"COOLIX","Bits":24,"Data":"0xB26BE0","DataLSB":"0x4DD607","Repeat":0,"IRHVAC":{"Vendor":"COOLIX","Model":-1,"Command":"Control","Mode":"Heat","Power":"On","Celsius":"On","Temp":30,"FanSpeed":"Max","SwingV":"Auto","SwingH":"Off","Quiet":"Off","Turbo":"Off","Econo":"Off","Light":"Off","Filter":"Off","Clean":"Off","Beep":"Off","Sleep":-1,"iFeel":"Off","SensorTemp":null}}
  - type: horizontal-stack
    cards:
      - type: button
        icon: mdi:fan-off
        name: Heat Swing Off
        show_name: true
        show_icon: true
        tap_action:
          action: call-service
          service: mqtt.publish
          service_data:
            topic: cmnd/WemosIR/IRsend
            payload: >-
              {"Protocol":"COOLIX","Bits":24,"Data":"0xB26BE0","DataLSB":"0x4DD607","Repeat":0,"IRHVAC":{"Vendor":"COOLIX","Model":-1,"Command":"Control","Mode":"Heat","Power":"On","Celsius":"On","Temp":30,"FanSpeed":"Max","SwingV":"Off","SwingH":"Off","Quiet":"Off","Turbo":"Off","Econo":"Off","Light":"Off","Filter":"Off","Clean":"Off","Beep":"Off","Sleep":-1,"iFeel":"Off","SensorTemp":null}}
      - type: button
        icon: mdi:fire-off
        name: Heat Off
        show_name: true
        show_icon: true
        tap_action:
          action: call-service
          service: mqtt.publish
          service_data:
            topic: cmnd/WemosIR/IRsend
            payload: >-
              {"Protocol":"COOLIX","Bits":24,"Data":"0xB27BE0","DataLSB":"0x4DDE07","Repeat":0,"IRHVAC":{"Vendor":"COOLIX","Model":-1,"Command":"Control","Mode":"Heat","Power":"Off","Celsius":"On","Temp":30,"FanSpeed":"Max","SwingV":"Off","SwingH":"Off","Quiet":"Off","Turbo":"Off","Econo":"Off","Light":"Off","Filter":"Off","Clean":"Off","Beep":"Off","Sleep":-1,"iFeel":"Off","SensorTemp":null}}
  - type: horizontal-stack
    cards:
      - type: button
        icon: mdi:snowflake
        name: Cool On
        show_name: true
        show_icon: true
        tap_action:
          action: call-service
          service: mqtt.publish
          service_data:
            topic: cmnd/WemosIR/IRsend
            payload: >-
              {"Protocol":"COOLIX","Bits":24,"Data":"0xB23F00","DataLSB":"0x4DFC00","Repeat":0,"IRHVAC":{"Vendor":"COOLIX","Model":-1,"Command":"Control","Mode":"Cool","Power":"On","Celsius":"On","Temp":17,"FanSpeed":"Max","SwingV":"Off","SwingH":"Off","Quiet":"Off","Turbo":"Off","Econo":"Off","Light":"Off","Filter":"Off","Clean":"Off","Beep":"Off","Sleep":-1,"iFeel":"Off","SensorTemp":null}}
      - type: button
        icon: mdi:fan
        name: Cool Swing On
        show_name: true
        show_icon: true
        tap_action:
          action: call-service
          service: mqtt.publish
          service_data:
            topic: cmnd/WemosIR/IRsend
            payload: >-
              {"Protocol":"COOLIX","Bits":24,"Data":"0xB26BE0","DataLSB":"0x4DD607","Repeat":0,"IRHVAC":{"Vendor":"COOLIX","Model":-1,"Command":"Control","Mode":"Cool","Power":"On","Celsius":"On","Temp":17,"FanSpeed":"Max","SwingV":"Auto","SwingH":"Off","Quiet":"Off","Turbo":"Off","Econo":"Off","Light":"Off","Filter":"Off","Clean":"Off","Beep":"Off","Sleep":-1,"iFeel":"Off","SensorTemp":null}}
  - type: horizontal-stack
    cards:
      - type: button
        icon: mdi:fan-off
        name: Cool Swing Off
        show_name: true
        show_icon: true
        tap_action:
          action: call-service
          service: mqtt.publish
          service_data:
            topic: cmnd/WemosIR/IRsend
            payload: >-
              {"Protocol":"COOLIX","Bits":24,"Data":"0xB26BE0","DataLSB":"0x4DD607","Repeat":0,"IRHVAC":{"Vendor":"COOLIX","Model":-1,"Command":"Control","Mode":"Cool","Power":"On","Celsius":"On","Temp":17,"FanSpeed":"Max","SwingV":"Off","SwingH":"Off","Quiet":"Off","Turbo":"Off","Econo":"Off","Light":"Off","Filter":"Off","Clean":"Off","Beep":"Off","Sleep":-1,"iFeel":"Off","SensorTemp":null}}
      - type: button
        icon: mdi:snowflake-off
        name: Cool Off
        show_name: true
        show_icon: true
        tap_action:
          action: call-service
          service: mqtt.publish
          service_data:
            topic: cmnd/WemosIR/IRsend
            payload: >-
              {"Protocol":"COOLIX","Bits":24,"Data":"0xB27BE0","DataLSB":"0x4DDE07","Repeat":0,"IRHVAC":{"Vendor":"COOLIX","Model":-1,"Command":"Control","Mode":"Cool","Power":"Off","Celsius":"On","Temp":17,"FanSpeed":"Max","SwingV":"Off","SwingH":"Off","Quiet":"Off","Turbo":"Off","Econo":"Off","Light":"Off","Filter":"Off","Clean":"Off","Beep":"Off","Sleep":-1,"iFeel":"Off","SensorTemp":null}}

```

**Comment by Repsionu** [comment]
And this code snippet required some kind of AI :-(
Do not think so- and expose less :-)
IMHO do not realize how AI is really controlled- and reusing sensible data...
Best, JR

**Comment by nao-pon** [comment]
Completed with d030012231600ed6ac4c2c43c644e8c7465c0a3b.

**Comment by fragolinux** [comment]
> And this code snippet required some kind of AI :-( Do not think so- and expose less :-) IMHO do not realize how AI is really controlled- and reusing sensible data... Best, JR

nothing harmful in there... i could have done by myself, but didn't want to loose time on such easy task, which chatgpt made in seconds... relax...

**Comment by SinanMQTT** [comment]
@Repsionu 
could you please tell us how you fixed the problem?


> Thanks for a speedy fix, IRHVAC online again :-)
